#!/bin/sh

abspath() {
cd "$(dirname "$1")"; printf "%s
" "$(pwd)/$(basename "$1")"
}

i="$1"

i="$(abspath "$i")"

o="$2"

o="$(abspath "$o")"

cd ~/dev/html2cup/

set -e

if [ -n "$o" ]; then
  ./bin/html2cup --body --php -- "$i" >"$o".new
  mv "$o".new "$o"
else
  ./bin/html2cup -- "$i"
fi

